### ISSUE TITLE
no Getting started or How to!

### ISSUE THREAD

**Issue by aminbh111** [uxnow/escpos.js#1]
escpos.js seems to be a good new alternative  printing solutions but without any documentation or examples ,it seems to be hard to understand the 3524 lines.

**Comment by jarvisaoieong** [comment]
We focus on make it stable now.
Better readme will be coming soon.

**Comment by uxnow** [comment]
please try to start with source code in L3107,
https://github.com/uxnow/escpos.js/blob/master/escpos.js#L3107

**Comment by uxnow** [comment]
we have updated the code, now source code is little, thank you!
